In [2]:
import random
import numpy as np
random.seed(0)
# 0 for non-diabetic; 1 otherwise

train_x = [[random.randint(0,1), float(random.randint(60,150))] for _ in range(2000)]

test_x = [[random.randint(0,1), float(random.randint(60,150))] for _ in range(400)]

# 0 for no-alert; 1 for alert
train_y = []
test_y = []

for x in train_x:
    if x[0] == 0:
        if 80 <= x[1] <= 120:
            train_y.append(int(0))
        else:
            train_y.append(int(1))
    else:
        if 80 <= x[1] <= 130:
            train_y.append(int(0))
        else:
            train_y.append(int(1))

for x in test_x:
    if x[0] == 0:
        if 80 <= x[1] <= 120:
            test_y.append(0)
        else:
            test_y.append(1)
    else:
        if 80 <= x[1] <= 130:
            test_y.append(0)
        else:
            test_y.append(1)
# def ary(x):
#   np.asarray(x)

# test_x = np.asarray(test_x)
# ary(train_x)
# ary(train_y)
# ary(test_x)
# ary(test_y)
print(test_x[:5])
print(test_y[:5])
# test_x.shape()

[[0, 81.0], [0, 137.0], [0, 116.0], [1, 87.0], [0, 123.0]]
[0, 1, 0, 0, 1]


In [0]:
test_x = np.asarray(test_x)
test_y = np.asarray(test_y)
train_x = np.asarray(train_x)
train_y = np.asarray(train_y)

In [0]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

In [0]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape = train_x[0].shape),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
model.fit(train_x, train_y, epochs=10)


Train on 2000 samples
Epoch 1/10
2000/2000 [==============================] - 0s 50us/sample - loss: 0.1684 - acc: 0.9225
Epoch 2/10
2000/2000 [==============================] - 0s 47us/sample - loss: 0.1687 - acc: 0.9290
Epoch 3/10
2000/2000 [==============================] - 0s 44us/sample - loss: 0.1770 - acc: 0.9255
Epoch 4/10
2000/2000 [==============================] - 0s 46us/sample - loss: 0.2110 - acc: 0.9095
Epoch 5/10
2000/2000 [==============================] - 0s 49us/sample - loss: 0.2015 - acc: 0.9180
Epoch 6/10
2000/2000 [==============================] - 0s 63us/sample - loss: 0.1985 - acc: 0.9165
Epoch 7/10
2000/2000 [==============================] - 0s 50us/sample - loss: 0.1806 - acc: 0.9235
Epoch 8/10
2000/2000 [==============================] - 0s 45us/sample - loss: 0.1920 - acc: 0.9160
Epoch 9/10
2000/2000 [==============================] - 0s 45us/sample - loss: 0.1767 - acc: 0.9220
Epoch 10/10
2000/2000 [==============================] - 0s 46us/sample - loss

In [0]:
model.evaluate(test_x, test_y)




400/400 [==============================] - 0s 196us/sample - loss: 0.0958 - acc: 0.9800


[0.09580090463161468, 0.98]

In [0]:
!pip install --quiet --upgrade tensorflow_federated
!pip install --quiet --upgrade tf-nightly


     |████████████████████████████████| 389kB 2.8MB/s 
     |████████████████████████████████| 1.8MB 53.1MB/s 
     |████████████████████████████████| 81kB 10.3MB/s 
     |████████████████████████████████| 2.2MB 43.9MB/s 
     |████████████████████████████████| 296kB 56.6MB/s 
     |████████████████████████████████| 86.3MB 64kB/s 
     |████████████████████████████████| 380.8MB 27kB/s 
     |████████████████████████████████| 3.8MB 39.2MB/s 
     |████████████████████████████████| 450kB 53.3MB/s 
     |████████████████████████████████| 81kB 10.7MB/s 
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.10.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement portpicker~=1.2.0, but you'll have portpicker 1.3.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
     |████████████████████████████████| 449.5MB 39kB/s 
     |████████████████████████████████| 46

In [0]:
import collections
import warnings
from six.moves import range
import numpy as np
import six
import tensorflow as tf
import tensorflow_federated as tff

In [6]:
warnings.simplefilter('ignore')

tf.compat.v1.enable_v2_behavior()

np.random.seed(0)

# NOTE: If the statement below fails, it means that you are
# using an older version of TFF without the high-performance
# executor stack. Call `tff.framework.set_default_executor()`
# instead to use the default reference runtime.
if six.PY3:
  tff.framework.set_default_executor(tff.framework.create_local_executor())

tff.federated_computation(lambda: 'Hello, World!')()

b'Hello, World!'

In [0]:
emnist_train, emnist_test = tff.simulation.datasets.emnist.load_data()


97402880/97398400 [==============================] - 1s 0us/step


In [0]:
import pandas as pd
import tensorflow as tf
import tensorflow_federated as tff
traindx = pd.DataFrame(train_x , columns = ['diabetic', 'blood pressure'])
traindy = pd.DataFrame(train_y, columns=['label'])
# client_id_colname = 'native.country' # the column that represents client ID
SHUFFLE_BUFFER = 1000
NUM_EPOCHS = 1

# inputdf = pd.DataFrame([train_x], columns = ['input'])
traindx.insert(0,'id', np.arange(len(traindx)))
traindx.insert(3, 'label', traindy['label'] )
# traindx.insert(4, 'input', inputdf['input'])

# split client id into train and test clients
client_ids = traindx['id']
train_client_ids = client_ids.sample(frac=0.8).tolist()
test_client_ids = [x for x in client_ids if x not in train_client_ids]

In [8]:
traindx[:5]

id  diabetic  blood pressure  label
0   0       1.0           113.0      0
1   1       0.0            93.0      0
2   2       1.0           111.0      0
3   3       1.0           121.0      0
4   4       1.0           134.0      1

In [0]:
def fed_dataloader(client_id):
  # a function which takes a client_id and returns a
  # tf.data.Dataset for that client
  client_data = traindx
  dataset = tf.data.Dataset.from_tensor_slices(client_data.to_dict('list'))
  dataset = dataset.shuffle(SHUFFLE_BUFFER).batch(1).repeat(NUM_EPOCHS)
  return dataset

train_data = tff.simulation.ClientData.from_clients_and_fn(
        client_ids=train_client_ids,
        create_tf_dataset_for_client_fn=fed_dataloader
    )
test_data = tff.simulation.ClientData.from_clients_and_fn(
        client_ids=test_client_ids,
        create_tf_dataset_for_client_fn=fed_dataloader
    )

In [0]:
train_data

In [0]:
example_dataset = train_data.create_tf_dataset_for_client(
        train_data.client_ids[0]
    )

In [11]:
print(type(example_dataset))
example_element = iter(example_dataset).next()
example_element['label'].numpy()
print(example_element)


<class 'tensorflow.python.data.ops.dataset_ops.RepeatDataset'>
{'id': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([619], dtype=int32)>, 'diabetic': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>, 'blood pressure': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([133.], dtype=float32)>, 'label': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>}


In [12]:
example_element['blood pressure']

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([133.], dtype=float32)>

In [0]:
NUM_CLIENTS = 10
NUM_EPOCHS = 10
BATCH_SIZE = 20
SHUFFLE_BUFFER = 500

def preprocess(dataset):

  def element_fn(element):
    # print('test')
    # print(element['id'], element['diabetic'], element['blood pressure'])
    # print('test2')
    return collections.OrderedDict([
        ('x', tf.reshape(element['blood pressure'], [-1])),
        ('y', tf.reshape(element['label'], [1])),
    ])

  return dataset.repeat(NUM_EPOCHS).map(element_fn).shuffle(
      SHUFFLE_BUFFER).batch(BATCH_SIZE)

preprocessed_example_dataset = preprocess(example_dataset)



In [0]:
def make_federated_data(client_data, client_ids):
  return [client_data.create_tf_dataset_for_client(x)
          for x in client_ids]


In [16]:
federated_train_data = make_federated_data(train_data, train_client_ids)


KeyboardInterrupt: ignored

In [21]:
sample_batch = tf.nest.map_structure(
    lambda x: x.numpy(), iter(preprocessed_example_dataset).next())

sample_batch


OrderedDict([('x', array([[126.],
                     [ 89.],
                     [ 64.],
                     [ 86.],
                     [ 78.],
                     [ 92.],
                     [ 78.],
                     [138.],
                     [120.],
                     [ 80.],
                     [103.],
                     [ 83.],
                     [137.],
                     [ 91.],
                     [109.],
                     [120.],
                     [124.],
                     [135.],
                     [ 70.],
                     [ 74.]], dtype=float32)), ('y', array([[0],
                     [0],
                     [1],
                     [0],
                     [1],
                     [0],
                     [1],
                     [1],
                     [0],
                     [0],
                     [0],
                     [0],
                     [1],
                     [0],
                     [0],
               

In [0]:
def create_compiled_keras_model():
  model = keras.models.Sequential([
      keras.layers.Flatten(input_shape = (1,)),
      keras.layers.BatchNormalization(),
      keras.layers.Dense(128, activation='relu'),
      keras.layers.BatchNormalization(),
      keras.layers.Dense(2, activation='softmax')
  ])

  model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])
  return model

def model_fn():
  keras_model = create_compiled_keras_model()
  return tff.learning.from_compiled_keras_model(keras_model, sample_batch)

In [25]:
iterative_process = tff.learning.build_federated_averaging_process(model_fn)


TypeError: ignored

In [0]:
state = iterative_process.initialize()


NameError: ignored

In [0]:
state, metrics = iterative_process.next(state, federated_train_data)
print('round  1, metrics={}'.format(metrics))

NameError: ignored

In [24]:
for round_num in range(1, 11):
  state, metrics = iterative_process.next(state, federated_train_data)
  print('round {:2d}, metrics={}'.format(round_num, metrics))

NameError: ignored